### ISSUE TITLE
docker-compose设置了账号密码和服务模式启动，但无法正常使用，大佬可以康康哪里写错了吗

### ISSUE THREAD

**Issue by Joackk** [zhile-io/pandora#47]
docker-compose文件内容如下
```
version: '3'
services:
  pandora:
    image: pengzhile/pandora
    stdin_open: true
    tty: true
    container_name: pandora-container
    environment:
      PANDORA_SERVER: 0.0.0.0:8080
      OPENAI_EMAIL: xxx
      OPENAI_PASSWORD: xxxx
    volumes:
      - ./data:/data
```
启动后提示输入账号密码
![image](https://github.com/zhile-io/pandora/assets/45162558/5469cc45-4bba-4d24-82cc-367059dc1c48)
